### ISSUE TITLE
Feature Request : rsyslog

### ISSUE THREAD

**Issue by erdoukki** [gSpotx2f/luci-app-log#2]
syslog-ng is verry instable.
So I replace it by rsyslog, which is more mature...
Is it possible to implement in luci-app-log the rsyslog /var/log/messages view ?
The centralized log view will be a must !

**Comment by gSpotx2f** [comment]
@erdoukki, logread tool from the syslog-ng package reads /var/log/messages ;)
You need to install syslog-ng (remove the logd first), then stop and disable it.
Start or restart rsyslog. Bingo!

**Comment by erdoukki** [comment]
ok, done for testing and works fine ! thanks...
But now it is luci-app-log which do not show hostname from /var/log/messages :
```
Mar 22 17:29:47 myNextCloud systemd[1]: systemd-tmpfiles-clean.service: Succeeded.
Mar 22 17:29:47 myNextCloud systemd[1]: Started Cleanup of Temporary Directories.
Mar 22 17:30:07 LPM dnsmasq-dhcp[32377]: not giving name klub.lpm.nddc.gk2.net to the DHCP lease of 10.4.2.116 because the name exists in /tmp/hosts/dhcp.cfg01411c with address 10.4.2.165
Mar 22 17:30:52 LPM uhttpd[2941]: luci: accepted login on /admin/services/syslog for root from 10.4.2.112

```

**Comment by gSpotx2f** [comment]
@erdoukki, [3257899](https://github.com/gSpotx2f/luci-app-log/commit/3257899a614e2cde87f23f3daab3b984d0e7409a)...

**Comment by erdoukki** [comment]
Great, thanks...
I still get only #, timestamps and messages in system log from a centralized log !
Correct and complete on default logging, with kenel and system logs, but on a rsyslog centralized /var/log/messages (tweaked with the logread from syslog-ng) I get only #, timestamps and messages.
No level, nor facilities, and still no host columns.

**Comment by gSpotx2f** [comment]
"Level" and "Facility" are only present in logd. The /var/log/messages does not contain this data at all.
About the "Host" column...
Reinstall the luci-app-log completely, clear your browser cache.
Restart the following OpenWrt services:
`/etc/init.d/rpcd restart`
`/etc/init.d/uhttpd restart`
`rm /tmp/luci-indexcache* /tmp/luci-modulecache/*`
It should be like [this](https://github.com/gSpotx2f/luci-app-log/blob/master/screenshots/03.jpg).

**Comment by erdoukki** [comment]
still no host...
here a screenshot : https://github.com/erdoukki/luci-app-log/blob/master/screenshots/Screenshot_2021-03-25%20LPM%20-%20System%20Log%20-%20LuCI.png

**Comment by gSpotx2f** [comment]
@erdoukki, please show the first 10 lines of your log (from /var/log/messages)

**Comment by erdoukki** [comment]
yes, sure : 
root@LPM:~# head /var/log/messages 
```
Mar 19 17:20:35 LPM :  [origin software="rsyslogd" swVersion="8.39.0" x-pid="1756" x-info="http://www.rsyslog.com"] start
Mar 19 17:20:35 LPM modprobe: xt_multiport is already loaded
Mar 19 17:20:35 LPM modprobe: xt_connmark is already loaded
Mar 19 17:20:35 LPM modprobe: xt_comment is already loaded
Mar 19 17:20:35 LPM modprobe: xt_length is already loaded
Mar 19 17:20:36 LPM Tor[2897]: Tor 0.4.4.5 running on Linux with Libevent 2.1.11-stable, OpenSSL 1.1.1j, Zlib 1.2.11, Liblzma N/A, and Libzstd N/A.
Mar 19 17:20:36 LPM Tor[2897]: Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Mar 19 17:20:36 LPM Tor[2897]: Read configuration file "/tmp/torrc".
Mar 19 17:20:36 LPM Tor[2897]: Processing configuration path "/etc/tor/torrc" at recursion level 1.
Mar 19 17:20:36 LPM Tor[2897]: Including configuration file "/etc/tor/torrc".
```

**Comment by gSpotx2f** [comment]
The log is ok, [here](https://www.imagevenue.com/ME135OMJ) is your log on my system.
See your previous [screenshot](https://raw.githubusercontent.com/erdoukki/luci-app-log/master/screenshots/Screenshot_2021-03-25%20LPM%20-%20System%20Log%20-%20LuCI.png), you are using an old version of the luci-app-log...

**Comment by erdoukki** [comment]
I am using the correct version of luci-app-log, but I needed to upgrade luci and luci-base to get the latest luci-app-log working correctly.
It now show hosts as requested !
And I can also filter on them.
Thanks
