### ISSUE TITLE
Why not available via plugin libary

### ISSUE THREAD

**Issue by NilsRo** [gSpotx2f/luci-app-log#3]
Hi,

looked for a better log analysis plugin without going via shell and your plugin looks great. Is there a reason why it is not available via plugin store in 21.02.2?

Cheers,
Nils

**Comment by stokito** [comment]
@gSpotx2f maybe you can create a PR into the Luci? You may ether add as a separate app or enhance the existing log page.
I realy just found the app while looked for another but thia definetelly looks useful
