### ISSUE TITLE
dmesg -T / --ctime human readable timestamps

### ISSUE THREAD

**Issue by aphorise** [gSpotx2f/luci-app-log#4]
A UI option to resolve times from boot (0) in human readable formats & using the current `uptime` to estimate starting time / date would be well appreciated.

Given the native [limitation with `dmesg` not supporting the paramters: `-T, --ctime: Print human-readable timestamps`](https://www.man7.org/linux/man-pages/man1/dmesg.1.html) this could be a great workp-around making the tool even more useful.

**Comment by gSpotx2f** [comment]
@aphorise, [8c9aba5](https://github.com/gSpotx2f/luci-app-log/commit/8c9aba52ae76a5edd39c182ec26e6e780f9647dc)

**Comment by aphorise** [comment]
It looks fantastic!
![image](https://user-images.githubusercontent.com/974854/180873418-ff6a3d44-5125-4ff0-9dcd-5258ae690aba.png)
Hey @gSpotx2f thank you! - this now make both default `Kernel Log` and yours useful.
