### ISSUE TITLE
Зависимости в пакете luci-i18n-log-viewer-ru_1.0-0_all.ipk

### ISSUE THREAD

**Issue by IojkinKot** [gSpotx2f/luci-app-log#5]
В зависимостях пакета luci-i18n-log-viewer-ru_1.0-0_all.ipk указан пакет luci-lua-runtime, а такого пакета нет для OpenWRT 21.02, поэтому русификатор не устанавливается. Раньше по моему такой зависимости не было и русификатор устанавливался без проблем.

**Comment by gSpotx2f** [comment]
>В зависимостях пакета luci-i18n-log-viewer-ru_1.0-0_all.ipk указан пакет luci-lua-runtime, а такого пакета нет для OpenWRT 21.02, поэтому русификатор не устанавливается. Раньше по моему такой зависимости не было и русификатор устанавливался без проблем.

Данная зависимость не конкретно этого пакета, а системы локализации в 23.05. luci-lua-runtime добавляется в список зависимостей автоматически при сборке пакета (сейчас я собираю пакеты в среде 23.05).
Похоже, в 23.05 окончательно выпилили lua из LuCI в отдельный пакет luci-lua-runtime. В предыдущих версиях OpenWrt такой зависимости небыло. Для 21.02 (и 22.03) можно попробовать установить пакет игнорируя зависимости (`--force-depends`):

    opkg --force-depends install luci-i18n-log-viewer-ru_1.0-0_all.ipk

либо нужно самостоятельно собирать пакет локализации для вашей версии OpenWrt. Также можно просто вытащить из пакета файл локализации `log-viewer.ru.lmo` и положить его на роутере в папку `/usr/lib/lua/luci/i18n`.
