### ISSUE TITLE
Добавить колонку "Программа" для системного журнала

### ISSUE THREAD

**Issue by IojkinKot** [gSpotx2f/luci-app-log#7]
Добрый день!

Можете добавить колонку "Программа" для системного журнала? Это строка после уровня сообщения и до двоеточия. Только квадратные скобки нужно исключить.

Пример:
Fri Apr  5 11:45:50 2024 authpriv.notice dropbear[18436]: Password auth succeeded for 'root' from 192.168.11.10:58487
Вот тут программа - это "dropbear"

**Comment by gSpotx2f** [comment]
Ещё одна колонка нормально не влезет в стандартный дизайн LuCI в теме bootstrap, придётся уменьшать ширину колонки сообщения (из-за горизонтальных отступов внутри ячеек), а в ней уже сейчас строки переносятся по два раза в некоторых записях. Поэтому и не стал выделять источник сообщения в отдельный столбец. Если необходимо, всегда можно отобрать записи из конкретного источника по фильтру текста самого сообщения.
