### ISSUE TITLE
Contribute to LUCI upstream

### ISSUE THREAD

**Issue by stokito** [gSpotx2f/luci-app-log#8]
The Luci now has a log viewer component:

https://github.com/openwrt/luci/blob/master/modules/luci-base/htdocs/luci-static/resources/tools/views.js

It can be used by a specific plugin to show only one service logs like here:
https://github.com/openwrt/luci/blob/master/applications/luci-app-adblock/htdocs/luci-static/resources/view/adblock/logread.js

So could you please improve it and extend with features that the plugin provides?
That would be helpful for all OpenWrt ecosystem

**Comment by gSpotx2f** [comment]
Small refactoring: [https://github.com/gSpotx2f/luci-app-log/commit/4af4f3f4658407ce447365def34fb6736db95436](https://github.com/gSpotx2f/luci-app-log/commit/4af4f3f4658407ce447365def34fb6736db95436)
Example log for a specific application: [mod-app-example](https://github.com/gSpotx2f/luci-app-log/tree/master/dev-mods-examples/mod-app-example)
